"""added new model correction

Revision ID: b570277ad793
Revises: 5cc734f238bf
Create Date: 2024-09-05 13:49:12.937896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b570277ad793'
down_revision = '5cc734f238bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeTeam', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('awayTeam', sa.String(length=100), nullable=False))

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=100), nullable=False))
        batch_op.drop_column('rusult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rusult', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('result')

    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_column('awayTeam')
        batch_op.drop_column('homeTeam')

    # ### end Alembic commands ###
